export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER_RECIPES = "GET_CURRENT_USER_RECIPES";
export const GET_SPECIFIC_RECIPE = "GET_SPECIFIC_RECIPE";
export const CREATE_NEW_RECIPE = "CREATE_NEW_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";