// Errors
export const GET_ERRORS = "GET_ERRORS";

// Users
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_INFO = "GET_USER_INFO";
export const SET_USER_INFO_LOADING = "SET_USER_INFO_LOADING";
export const FOLLOW_USER = "FOLLOW_USER";
export const ADD_FOLLOWING = "ADD_FOLLOWING";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const REMOVE_FOLLOWING = "REMOVE_FOLLOWING";
export const EDIT_USER = "EDIT_USER";

// Recipes
export const GET_CURRENT_USER_RECIPES = "GET_CURRENT_USER_RECIPES";
export const GET_SPECIFIC_RECIPE = "GET_SPECIFIC_RECIPE";
export const CREATE_NEW_RECIPE = "CREATE_NEW_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const CLEAR_SELECTED_RECIPE = "CLEAR_SELECTED_RECIPE";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const SET_RECIPES_LOADING = "SET_RECIPES_LOADING";
export const GET_USER_RECIPES = "GET_USER_RECIPES";
export const GET_RECENT_RECIPES = "GET_RECENT_RECIPES";
export const LIKE_RECIPE = "LIKE_RECIPE";
export const UNLIKE_RECIPE = "UNLIKE_RECIPE";

// Comments
export const CREATE_COMMENT = "CREATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";

// Recipe Book
export const GET_USER_RECIPE_BOOK = "GET_USER_RECIPE_BOOK";
export const ADD_TO_RECIPE_BOOK = "ADD_TO_RECIPE_BOOK";
export const DELETE_FROM_RECIPE_BOOK = "DELETE_FROM_RECIPE_BOOK";
export const SET_RECIPEBOOK_LOADING = "SET_RECIPEBOOK_LOADING";
export const CREATE_RECIPE_BOOK = "CREATE_RECIPE_BOOK";
export const REMOVE_RECIPE_FROM_RECIPEBOOK = "REMOVE_RECIPE_FROM_RECIPEBOOK";
export const GET_CURRENT_USER_RECIPEBOOK = "GET_CURRENT_USER_RECIPEBOOK";


// Shopping list
export const CREATE_SHOPPING_LIST = "CREATE_SHOPPING_LIST";
export const GET_SHOPPING_LIST = "GET_SHOPPING_LIST";
export const ADD_TO_SHOPPING_LIST = "ADD_TO_SHOPPING_LIST";
export const PICKUP_ITEM = "PICKUP_ITEM";
export const PUTBACK_ITEM = "PUTBACK_ITEM";
export const CLEAR_SHOPPING_LIST = "CLEAR_SHOPPING_LIST";
export const SET_SHOPPING_LIST_LOADING = "SET_SHOPPING_LIST_LOADING";
export const DELETE_SHOPPING_LIST_ITEM = "DELETE_SHOPPING_LIST_ITEM";
export const ADD_MANY_TO_SHOPPING_LIST = "ADD_MANY_TO_SHOPPING_LIST";


// Admin
export const GET_ADMIN_DATA = "GET_ADMIN_DATA";
export const SET_ADMIN_STATUS = "SET_ADMIN_STATUS";
export const REVOKE_ADMIN_STATUS = "REVOKE_ADMIN_STATUS";